name: pylint
on: [push, pull_request]

jobs:
  PEP8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python lint libraries
        run: |
          python -m pip install --upgrade pip
          pip install autopep8 autoflake isort black

      - name: Check for showstoppers
        run: |
          autopep8 --verbose --in-place --recursive --aggressive --aggressive ./*.py

      - name: Remove unused imports and variables
        run: |
          autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports .

      - name: Lint with isort and black
        run: |
          isort userbot/modules/*.py
          black userbot/modules/*.py

      - name: Configure Git
        run: |
          git config --global user.email "niteshraj231@outlook.com"
          git config --global user.name "Nitesh"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit --signoff -m "Apply automatic formatting"
            git push origin HEAD:${{ github.ref }}
          else
            echo "No changes to commit"
          fi